---
- name: setup LAMP Web Server
  hosts: ubuntu
  become: true
  gather_facts: yes
  tasks:
    - name: install Apache Web Server
      import_role:
        name: apache_php
    - name: flush handlers
      meta: flush_handlers
    - name: install mysql server
      import_role:
        name: mysql
    - name: check the welcome page
      command: curl "http://{{ inventory_hostname }}"
      delegate_to: 127.0.0.1
      register: result
    - name: display the welcome page
      debug:
        msg: "{{ result.content }}"
  