---
- name: install MySQL Server
  package:
    name: "{{ item }}"
    state: installed
    with_items:
      - mysql-server-core-5.5
      - mysql-client-core-5.5
      - libmysqlclient-dev
      - python-mysqldb
      - mysql-server
      - mysql-client

- name: Start the MySQL service
  service:
    name: mysql 
    state: started

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Create deploy user for mysql
  mysql_user: user="linhnh" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

- name: Ensure anonymous users are not in the database
  mysql_user: user='' host=$item state=absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database with name 'student'
  mysql_db:
    name: student
    state: present

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: insert student data into database  
  mysql_db: 
    name: student
    state: import 
    target: /tmp/dump.sql 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
