---
- name: install MySQL Server
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - 'libmysqlclient-dev'
    - 'python-mysqldb'
    - 'mysql-server'
    - 'mysql-client'

- name: Start the MySQL service
  service:
    name: mysql 
    state: started

# - name: Sets the root password
#   mysql_user:
#     name: root
#     password: "{{ mysql_root_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Update mysql root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{item}}"
    password: "{{ mysql_root_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database with name 'student'
  mysql_db:
    name: student
    state: present

- name: insert student data into database  
  mysql_db: 
    name: student
    state: import 
    target: /tmp/dump.sql 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
